version: "3.5"

services:
  # Database
  postgres:
    image: postgres:11.2
    restart: unless-stopped
    container_name: "${APP_NAME}-postgres"
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - "15432:5432"
  
  # Redis
  redis:
    image: redis:5-alpine
    restart: unless-stopped
    container_name: "${APP_NAME}-redis"
    ports:
        - "16379:6379"
  
  # GraphQL
  server:
    build:
        context: .
        dockerfile: Dockerfile
    user: "node"
    restart: unless-stopped
    working_dir: /home/node/app
    container_name: "${APP_NAME}-server"
    links:
      - postgres
      - redis
    depends_on:
      - postgres
      - redis
    environment:
      - NODE_ENV=production
    volumes:
      - ./:/home/node/app
    ports:
      - ${PORT}:${PORT}
    command: "yarn run startup:prod"
