version: '3.5'

x-networks:
  &default-networks
  networks:
  - app-network

networks:
    app-network:
        driver: bridge
        name: "${APP_NAME}-network"

services:
  # Database
  postgres:
    << : *default-networks
  
  # Redis
  redis:
    << : *default-networks
  
  # GraphQL
  server:
    << : *default-networks
    environment:
      - NODE_ENV=development
    command: "yarn run startup:dev"
  
  # PG Admin
  pgadmin:
    << : *default-networks
    image: dpage/pgadmin4
    container_name: "${APP_NAME}-pgadmin4"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_USER}
      PGADMIN_DEFAULT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - $PWD/data/pgadmin4/servers.json:/pgadmin4/servers.json
    ports:
      - "16543:80"
    links:
      - postgres
    depends_on:
      - postgres
    logging:
      driver: none